server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: orderuser
    password: orderpass
  jpa:
    hibernate:
      ddl-auto: update
  graphql:
    graphiql:
      enabled: true

spring.kafka.bootstrap-servers: localhost:9092